---
- name: be sure libselinux-python is installed
  package:
    name: libselinux-python
    state: present

- name: disable selinux
  selinux: state=disabled

- name: disable firewall
  service: name=iptables state=stopped enabled=no

- name: ensure root has ssh key generated
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_file: .ssh/id_rsa

- name: fetch roots public key
  command: cat /root/.ssh/id_rsa.pub
  register: root_ssh_pub_key

- name: accept root@labcontroller ssh key locally
  become: true
  local_action: authorized_key user=root key={{ root_ssh_pub_key.stdout }}

- name: ensure sshd runs locally to read local ssh hostkeys
  become: true
  local_action: service name=sshd enabled=yes state=started

- name: read local ssh hostkey
  local_action: command ssh-keyscan -T 10 -t rsa {{ network.ip_address }}
  register: local_ssh_host_key

- name: add host key to known hosts file for root@labcontroller
  known_hosts:
    key: "{{ local_ssh_host_key.stdout }}"
    name: "{{ network.ip_address }}"
