---
- debug:
    msg: "No SSH key set without which you can not log into beaker-in-a-box. Set the user_key_path variable to a valid SSH public key filename"
  failed_when: not user_key

- name: ensure local packages are installed for the playbook
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - libselinux-python
    - python-lxml
